### ISSUE TITLE
Time until expired is unsigned

### ISSUE THREAD

**Issue by jan2000** [a-schild/zabbix-ssl#2]
The values for the lifetime items are stored as unsigned numbers, causing data collection to fail once a certificate is expired because the negative numbers are not valid for the value type.

The trigger `... certificate on {HOSTNAME} expired` is never triggered because the the condition `ssltls.check[...,lifetime].last()}<0`will never be satisfied.

This can be fixed by setting `<value_type>` to 0 (numeric float) for the lifetime items.

**Comment by a-schild** [comment]
Thanks, it fixed.
