### ISSUE TITLE
Zabbix template import failed

### ISSUE THREAD

**Issue by rtau-t24** [a-schild/zabbix-ssl#3]
When trying to import Template_App_HTTPS_Autodiscovery.xml on Zabbix 3.4, the import failed, mentioning that the value type 'Numeric (float)' for the function 'str(sha1)' is incorrect. 

After removing the offending part of the expression, getting the template imported, and changing the value type of the item prototype "HTTPS certificate digest mode {#SSLNAME}" from 'Numeric (float)' to 'Text', the expression could be restored to the original one without problem.

https://github.com/a-schild/zabbix-ssl/blob/8163c4600bf848b1c785739bde8ca89186a4b69b/Template_App_HTTPS_Autodiscovery.xml#L123

**Comment by a-schild** [comment]
Updated templates to work with Zabbi 3.4
