### ISSUE TITLE
Zabbix Template import all (HTTPS_Service AND HTTPS_Autodiscovery)

### ISSUE THREAD

**Issue by dataCore** [a-schild/zabbix-ssl#4]
Shouldn't it be possible, to import both templates? I have a server with many SNI-Pages but also an other server with just one page. So it would be great to use both templates... If I import all templates, i receive an exception with the last one for the multiple-SNI-Pages: **Template_App_HTTPS_Autodiscovery.xml**

Zabbix-Server 3.4

> Import Fails: Details
> Created: Item "HTTPS service is running" on "Template App HTTPS Service Autodiscovery".
> Updated: Discovery rule "HTTPS sites" on "Template App HTTPS Service Autodiscovery".
> Created: Item prototype "HTTPS certificate end date {#SSLNAME}" on "Template App HTTPS Service Autodiscovery".
> Created: Item prototype "HTTPS certificate time until expire {#SSLNAME}" on "Template App HTTPS Service Autodiscovery".
> Created: Item prototype "HTTPS service running {#SSLNAME}" on "Template App HTTPS Service Autodiscovery".
> Created: Item prototype "HTTPS sslv3 poodle vulnerable {#SSLNAME}" on "Template App HTTPS Service Autodiscovery".
> Created: Item prototype "HTTPS certificate start date {#SSLNAME}" on "Template App HTTPS Service Autodiscovery".
> Incorrect item value type "Numeric (float)" provided for trigger function "str(sha1)".

Any tipp? Thanks for the good work!

**Comment by a-schild** [comment]
Updated templates to work with Zabbix 3.4
