### ISSUE TITLE
ipv6 not working

### ISSUE THREAD

**Issue by robertolumbreras** [a-schild/zabbix-ssl#6]
Hi,

when HOST is an IPv6 address openssl s_client -connect 2001::2:33:4:25 does not work and it returns "argument malformed or ambiguous".

I got it fixed with the following patch

[ipv6.txt](https://github.com/a-schild/zabbix-ssl/files/2392901/ipv6.txt)

**Comment by a-schild** [comment]
@rover0 Thanks for the patch
