### ISSUE TITLE
scripts not working in Alpine Linux

### ISSUE THREAD

**Issue by magiruuvelvet** [a-schild/zabbix-ssl#9]
All results are empty, only the "simple" check works. Which renders this plugin useless in the official Alpine Linux based docker container.

I will try to fix this myself and maybe make a pull request if it doesn't break on other distros.

**Comment by magiruuvelvet** [comment]
I found the issue. It's the `timeout` command from the busybox binary. It requires the `-t` switch before the seconds. This breaks on literally every other distro.

I will just leave this issue open in case other people suffer from the same problem.

**Comment by a-schild** [comment]
Where do you have seen a reference to busybox?

**Comment by magiruuvelvet** [comment]
on Alpine Linux the timeout command resolves to busybox

```sh
bash-4.4# which timeout
/usr/bin/timeout
bash-4.4# readlink /usr/bin/timeout
/bin/busybox
bash-4.4# 
```

**Comment by a-schild** [comment]
I added a note about this in the readme file.
Thanks for reporting
